### ISSUE TITLE
Dates are invalid

### ISSUE THREAD

**Issue by MathijsV** [Pluxbox/radiomanager-javascript-client#1]
Every date returned by the javascript API is an invalid date object. This is caused by the explicit stripping of the T-character in the date string returned from the server.

With 2019-01-21T13:15:22+01:00 returned as date string from the server:
> new Date('2019-01-21T13:15:22+01:00')
< Mon Jan 21 2019 13:15:22 GMT+0100 (CET) // Works
> new Date(('2019-01-21T13:15:22+01:00').replace(/T/i, ' '))
< Invalid Date // Doesn't work
> new Date(('2019-01-21T13:15:22').replace(/T/i, ' '))
< Invalid Date // Still doesn't work

The simple solution would be to not strip the T-character from the date string before creating a Date object (in ApiClient.js - parseDate).

**Comment by Siebe** [comment]
Hi MathijsV,

We're not able to reproduce this error. What version of NodeJS are you using to run the SDK?

**Comment by MathijsV** [comment]
No NodeJS, it runs in a browser. Or is that not what this SDK is for?;-)

**Comment by Siebe** [comment]
Hey Mathijs,

Actually not :} 
Although the (generated) readme shows the option to use the SDK in a browser, that would mean the API key will need to be distributed to any client side applications as well and that is something we don't recommend or support at all.
For the next update of the SDK we will look into to the possibility to adapt the readme for this.
